### PR TITLE
fix: image tag format throw error

### LINKED ISSUE #72: foramt image tag throw error
Before you submit an issue we recommend you drop into the [Gitter community](https://gitter.im/Prettyhtml/Lobby) and ask any questions you have or mention any problems you've had getting started with prettyhtml.

## 🐛 Bug Report

format a <image> tag, throw Error.

## To Reproduce

Config: Defaull config

Paste your markup here:

```html
<template>
    <div>
        <image src="http://google.com">
    </div>
</template>
```

## Expected behavior

Paste the results here:

```html
<template>
    <div>
        <image src="http://google.com" />
    </div>
</template>
```

## Context

  Vue or html

## Your Environment

- Prettyhtml version: @starptech/prettyhtml@0.8.2
- NodeJs version:8.12.0
- Environment name and version:
- Operating System and version: macos

### PR DESCRIPTION
**Pull request by xiaomingplus**
fix #72 

Hi,I don't think image should a valid tag in html, so I remove the void tag from html-void-elements.

here are the expected examples:

input: 
 ```html
<template>
  <div>
    <image src="http://google.com" />
  </div>
</template>
```

output:

```html
<template>
  <div>
    <image src="http://google.com" />
  </div>
</template>

```

or,input:

```html
    <image src="http://google.com"></image>

```

output:

```html
   <image src="http://google.com"></image>
```

or ,input : 

```html
<image src="">
```

output:

```html
<image src="" />
```

### CODE REVIEW

File: packages/prettyhtml-hast-to-html/lib/index.js [hunk 1]
```diff
@@ -9,6 +9,16 @@ const repeat = require('repeat-string')
 
 module.exports = toHTML
 
+function arrayRemove(arr, value) {
```
Comment (StarpTech) [inline packages/prettyhtml-hast-to-html/lib/index.js]: Please use the prettier config of the project.

File: packages/webparser/src/html_tags.ts [hunk 2]
```diff
@@ -313,7 +313,6 @@ const TAG_DICTIONARY: { [name: string]: string } = {
 
   I: 'i',
   IMG: 'img',
-  IMAGE: 'image',
```
Comment (StarpTech) [inline packages/webparser/src/html_tags.ts]: Please add a test in the webparser package.

File: packages/prettyhtml-hast-to-html/lib/index.js [hunk 3]
```diff
@@ -9,6 +9,16 @@ const repeat = require('repeat-string')
...
+
+    return arr.filter(function(ele){
+        return ele != value;
+    });
+ 
+}
+/* For remove invalid html tag image  */
+voids = arrayRemove(voids,'image')
```
Comment (StarpTech) [inline packages/prettyhtml-hast-to-html/lib/index.js]: Add a test that verifies that the image is stringified correctly.

**Comment by StarpTech** [comment]
Hi @xiaomingplus the PR looks good except that the code isn't formatted with prettier and you didn't add tests.

**Comment by xiaomingplus** [comment]
Ok,I agree it,I'll give a pull request for that

**Comment by xiaomingplus** [comment]
if we treat ```image``` as a custom component, the custom default format code can't through the vetur default template check..
image

image

Can you give some advise?

**Comment by StarpTech** [comment]
@xiaomingplus I also double check it. The browsers will replace `image` with `img` even when it contains no `src` attribute. `image` can't be used as element selector in vue https://codesandbox.io/s/jpl947mrry. Since it collides with the ecosystem we should treat `image` as a self-closing tag. What a tedious case 😄

**Comment by xiaomingplus** [comment]
Actually,I use vue for weex(a react native like buy use vue) development,weex  provide a image component, https://weex.apache.org/references/components/image.html

So,treat ```image``` as  self-closing tag meaning?Can you give some expected output?

**Comment by StarpTech** [comment]
@xiaomingplus for me it looks like that weex is no real html framework. The markup won't reach a native browser.

> However, Weex is not a front-end framework. Indeed, front-end frameworks are just the syntax layer or DSL (Domain-specific Language) of Weex, they are decoupled from native render engines. In another word, Weex does not rely on any specific front-end frameworks. With the evolution of the technology, Weex can integrate more widely used front-end frameworks as well.

Therefore I don't want to support it in first instance.

This is an important info:

> Note: The HTML spec defines <image> as a synonym for  while parsing HTML. This specific element and its behavior only apply inside SVG documents or inline SVG.

Try this in prettyhtml, it behaves correctly:

```html
<svg>
<image src="http://google.com"></image>
</svg>
<image src="http://google.com"></image>
```
output
```html
<svg>
<image src="http://google.com"></image>
</svg>
<image src="http://google.com">
```
Finally there is no change needed. `image` should be never used as an element selector out of svg. I'm fine with that.

**Comment by StarpTech** [comment]
But I will prepare a fix so that no invalid markup is generated.

**Comment by xiaomingplus** [comment]
but,if you include your output in ```div```,it will throw a error.

input :

```html
<div>
<svg>
<image src="http://google.com"></image>
</svg>
<image src="http://google.com">
</div>
```

it throw a error.

I think you can merge the pull request simply.  :)

**Comment by StarpTech** [comment]
Hi @xiaomingplus indeed the PR looks good I've worked on the same solution. I missing some test I will add them to the PR.

**Comment by xiaomingplus** [comment]
Thanks~
